### ISSUE TITLE
More efficient way to add string to cell

### ISSUE THREAD

**Issue by mikeroher** [manuelemaggi/MMHorizontalListView#1]
Hey, thanks a lot for an awesome view! It was exactly what I needed. However, I'm currently trying to add two labels to each cell: a title and subtitle (similar to a TableView cell).

However, after an half hour of fighting it, I'm still confused. Where should I add the labels? I'm currently trying to add two UILabel's to the `MMHorizontalListView` class and two NSString's to the `MMHorizontalListViewCell`. 

After I initialize the labels in the `initialize` method, I set the frame, text (from the cell's new title and subtitle strings) and add the label to the cell in the `- (void)addCellAtIndex:(NSInteger)index;` method. It's not going to well..It keeps crashing before starting up.

UPDATE: So I tried the second method and it worked! Adding a label where the cell is initialized which makes logical sense now that I think about it...

Thanks!

**Comment by ozamihir1990** [comment]
Hey, thanks for your horizontal ListView. I am currently trying to add two labels and one image view to each cell. I added this Labels and image view in cellAtIndex Method. Please see my code as below: 

#pragma mark -  MMHorizontalListView Delegate Method
- (NSInteger)MMHorizontalListViewNumberOfCells:(MMHorizontalListView *)horizontalListView {
    return 8;
}
- (CGFloat)MMHorizontalListView:(MMHorizontalListView *)horizontalListView widthForCellAtIndex:(NSInteger)index {
    //return (arc4random() % 160)+ 20;
    return 150;
}

- (MMHorizontalListViewCell*)MMHorizontalListView:(MMHorizontalListView *)horizontalListView cellAtIndex:(NSInteger)index {
    MMHorizontalListViewCell *cell = [horizontalListView dequeueCellWithReusableIdentifier:@"test"];
    if (!cell)
    {
        cell = [[MMHorizontalListViewCell alloc] initWithFrame:CGRectMake(0, 0, 160, 160)];
        cell.reusableIdentifier = @"test";
        
        imgProductView = [[UIImageView alloc] initWithFrame:CGRectMake(20, 0, 90, 90)];
        lblProductTitle = [[UILabel alloc] initWithFrame:CGRectMake(20, 90, 100, 18)];
        
        imgProductView.contentMode = UIViewContentModeScaleAspectFit;
    }
    cell.backgroundColor = [UIColor lightGrayColor];
    
    //[imgProductView setCenter:CGPointMake(cell.bounds.size.width/2, cell.bounds.size.height/2)];
    //[imgProductView drawInRect:CGRectMake((cell.frame.size.width/2) - (imgProductView.image.size.width/2), (cell.frame.size.height / 2) - (imgProductView.image.size.height / 2), imgProductView.image.size.width, imgProductView.image.size.height)];
    
    lblProductTitle.text = [arrProductTitle objectAtIndex:index];
    NSLog(@"index = %@ ",[self.imagesData objectAtIndex:index]);
    imgProductView.image = [UIImage imageNamed:[self.imagesData objectAtIndex:index]];

    [cell addSubview:self.lblProductTitle];
    [cell addSubview:imgProductView];
    //[cell setBackgroundColor:[UIColor colorWithRed:(arc4random() % 255)/255.0 green:(arc4random() % 255)/255.0 blue:(arc4random() % 255)/255.0 alpha:1.0]];
    imgProductView= nil;
    
    return cell;
}

Above code is not working for me. I need your help to add uiimagevie horizontally center and two labels which are below the uiimage.

**Comment by manuelemaggi** [comment]
Hi,

this code is confusing me , I see where you allocate 'imgProductView' and 'lblProductTitle' but I don't see where you declare them, also this code here:

[cell addSubview:self.lblProductTitle];
[cell addSubview:imgProductView];

in one case you are refering to 'self.lblProductTitle' are them properties of the view controller that is implementing the  MMHorizontalListView delegate ?

if this is the case that's your problem, I suggest you to create a subclass of MMHorizontalListViewCell and add there your imageView and the label and access them as properties to set the content
