### ISSUE TITLE
ios 9 - crash Cannot form weak reference to instance (0x16b5ba00) of class MMHorizontalListView

### ISSUE THREAD

**Issue by johndpope** [manuelemaggi/MMHorizontalListView#3]
I think it's related to this 

http://stackoverflow.com/questions/10904990/objective-c-library-cannot-form-weak-reference-to-instance-of-class

@interface MMHorizontalListView : UIScrollView <UIScrollViewDelegate, UIGestureRecognizerDelegate> {

```
@private

__unsafe_unretained id<UIScrollViewDelegate> _scrollViewDelegate;
__unsafe_unretained id<MMHorizontalListViewDelegate>  _horizontalListDelegate;

NSRecursiveLock *_mainLock;
NSMutableArray *_cellQueue;
NSMutableDictionary *_visibleCells;
NSMutableArray *_cellFrames;
NSMutableArray *_selectedIndexes;
NSMutableArray *_highlightedIndexes;
```

}

**Comment by johndpope** [comment]
I ripped out the __unsafe_unretained and it stopped crashing. maybe not ideal.

**Comment by cbhgreat2016** [comment]
I fix this bug.

**Comment by cbhgreat2016** [comment]
- (void)setDelegate:(id<MMHorizontalListViewDelegate>)delegate {
  //Bug fix
  if (delegate) {
      [super setDelegate:self];
  } else {
      [super setDelegate:nil];
  }
  _horizontalListDelegate = delegate;
  }
